Repository Keerat666/ExpressJS-Starter-Template, pull requests merged in 2022-10, with the labels that each got.

#6 Hashing of password added
  .gitignore
  controllers/users.js
  middlewares/crud.js
  models/users.js
  package-lock.json
  package.json
Labels: good first issue, hacktoberfest-accepted, good-first-issue, thanks-for-contributing

#7 Feature (schema) Added blog schema
  models/blog.js
Labels: hacktoberfest-accepted, thanks-for-contributing

#8 Added e-commerce product functional model
  models/e-commerce product.js
Labels: hacktoberfest-accepted, thanks-for-contributing

#9 Feature (schema) Added Social media post schema.
  models/posts.js
Labels: hacktoberfest-accepted
